### ISSUE TITLE
FOOTER

### ISSUE THREAD

**Issue by tvgc** [claudiocsx/one_page-projec_grupo_telegram#7]

**Comment by Jonatan1103** [comment]
Boa noite Thales, deixei uma classe chamada :

```html
<div class="exemplo"></div>
```

Foi pra poder ver como ia ficar com o tamanho real da pagina, pode tirar ela quando for fazer o merge.

```html
    <div class="exemplo"></div>
    <!--
      - #FOOTER
    -->
    <footer class="c-footer">
      <aside class="footer__aside">
        <div class="aside__info">
          <h2 class="aside__title">
```

**Comment by tvgc** [comment]
Bom dia! 

Recebido sua mensagem. Quando você liberar para fazer a merge eu fecharei esta issue.

**Comment by Jonatan1103** [comment]
pode fazer  a merge...

**Comment by tvgc** [comment]
Bom dia!

Fiz a merge e não houve nenhum confito.

Mas gostaria de sugerir alguns detalhes para mudança:

- Acredito que o título do aside se aproximaria mais do template original caso houvesse a tag <br> entre as palavras "your" e "skills".
![Image](https://user-images.githubusercontent.com/90291719/183259939-eb7738aa-d726-4cee-81f7-55efa4a51746.png)

- Seria interessante a utilização das classes reutilizáveis ao máximo, uma vez que auxiliaria na mudança do código de maneira mais rápida e fluida. Uma sugestão seria trocar a classe footer__header-title por title-level-3 com a utilização da tag h3, pois se aproxima mais do padrão das demais sessões. Daí, so restaria trocar a cor. Flataria ainda a troca da classe container pela classe reutilizável criado.

- Por fim, gostaria de dizer que criei duas classes para deixar o icone chevron maior e centralizado.
como estava: ![Image](https://user-images.githubusercontent.com/90291719/183260140-09f20795-ebe5-412a-9b2f-3bc160f52d36.png)
como ficou: ![Image](https://user-images.githubusercontent.com/90291719/183260158-10e8fc4b-26db-4be2-86e6-44d4b4c2a78c.png)

**Comment by Jonatan1103** [comment]
estarei arrumando assim que possivel (acredito que amanhã)...  Estava focado na entrega de um exercício do curso.

**Comment by Jonatan1103** [comment]
Feito as alterações

**Comment by tvgc** [comment]
Verificado código e feito merge. 

Ficou muito bom; e também gostei da animação no botão chevrom.
