### ISSUE TITLE
Componente botão preto

### ISSUE THREAD

**Issue by tvgc** [claudiocsx/one_page-projec_grupo_telegram#9]
Confecção de boão preto (componente).

**Comment by Jonatan1103** [comment]
Finalizei a estilização do botão da versão mobile.
Deixei os botões já em suas respectivas seções. para não haver erro na hora de usar o icon incorreto ou com tamanho diferente.
Falando em icon não achei nenhum 100% igual, peguei o que mais se aproximava do template.

**Comment by tvgc** [comment]
Fiz a merge da sua branch com a main. O que eu fiz de diferente foi alterar o local da classe do botão no css, pois o local mais adequado seria na área de classes reutilizáveis.

Obrigado!
